import type { Metadata } from 'next';
import { ClerkProvider, Show, SignUp } from '@clerk/nextjs';
import { Montserrat, Geist_Mono } from 'next/font/google';
import './globals.css';

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${montserrat.variable} ${geistMono.variable} dark bg-background text-foreground antialiased`}
      >
        <ClerkProvider>
          <Show when='signed-out'>
            <main className='min-h-screen flex items-center justify-center p-6'>
              <SignUp routing='hash' />
            </main>
          </Show>
          <Show when='signed-in'>{children}</Show>
        </ClerkProvider>
      </body>
    </html>
  );
}
